config/routes.rb
CtrEstoque::Application.routes.draw do
  resources :detalhes

  resources :pedidos

  resources :items

  resources :enderecos

  resources :clientes

  

end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
  belongs_to :cliente
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: [:show, :edit, :update, :destroy]

  # GET /enderecos
  # GET /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1
  # GET /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos
  # POST /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to @endereco, notice: 'Endereco was successfully created.' }
        format.json { render action: 'show', status: :created, location: @endereco }
      else
        format.html { render action: 'new' }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1
  # PATCH/PUT /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to @endereco, notice: 'Endereco was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1
  # DELETE /enderecos/1.json
  def destroy
    @endereco.destroy
    respond_to do |format|
      format.html { redirect_to enderecos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endereco_params
      params.require(:endereco).permit(:rua, :numero, :cliente_id)
    end
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/views/enderecos/_form.html.erb
<%= form_for(@endereco) do |f| %>
  <% if @endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
      <% @endereco.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rua %><br>
    <%= f.text_field :rua %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :cliente %><br>
    <%= f.text_field :cliente %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enderecos/edit.html.erb
<h1>Editing endereco</h1>

<%= render 'form' %>

<%= link_to 'Show', @endereco %> |
<%= link_to 'Back', enderecos_path %>

app/views/enderecos/index.html.erb
<h1>Listing enderecos</h1>

<table>
  <thead>
    <tr>
      <th>Rua</th>
      <th>Numero</th>
      <th>Cliente</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @enderecos.each do |endereco| %>
      <tr>
        <td><%= endereco.rua %></td>
        <td><%= endereco.numero %></td>
        <td><%= endereco.cliente %></td>
        <td><%= link_to 'Show', endereco %></td>
        <td><%= link_to 'Edit', edit_endereco_path(endereco) %></td>
        <td><%= link_to 'Destroy', endereco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endereco', new_endereco_path %>

app/views/enderecos/new.html.erb
<h1>New endereco</h1>

<%= render 'form' %>

<%= link_to 'Back', enderecos_path %>

app/views/enderecos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rua:</strong>
  <%= @endereco.rua %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @endereco.numero %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @endereco.cliente %>
</p>

<%= link_to 'Edit', edit_endereco_path(@endereco) %> |
<%= link_to 'Back', enderecos_path %>