config/routes.rb
CtrEstoque::Application.routes.draw do
  resources :detalhes

  resources :pedidos

  resources :items

  resources :enderecos

  resources :clientes

  

end

app/models/detalhe.rb
class Detalhe < ActiveRecord::Base
  belongs_to :item_id
end

app/controllers/detalhes_controller.rb
class DetalhesController < ApplicationController
  before_action :set_detalhe, only: [:show, :edit, :update, :destroy]

  # GET /detalhes
  # GET /detalhes.json
  def index
    @detalhes = Detalhe.all
  end

  # GET /detalhes/1
  # GET /detalhes/1.json
  def show
  end

  # GET /detalhes/new
  def new
    @detalhe = Detalhe.new
  end

  # GET /detalhes/1/edit
  def edit
  end

  # POST /detalhes
  # POST /detalhes.json
  def create
    @detalhe = Detalhe.new(detalhe_params)

    respond_to do |format|
      if @detalhe.save
        format.html { redirect_to @detalhe, notice: 'Detalhe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @detalhe }
      else
        format.html { render action: 'new' }
        format.json { render json: @detalhe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detalhes/1
  # PATCH/PUT /detalhes/1.json
  def update
    respond_to do |format|
      if @detalhe.update(detalhe_params)
        format.html { redirect_to @detalhe, notice: 'Detalhe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @detalhe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detalhes/1
  # DELETE /detalhes/1.json
  def destroy
    @detalhe.destroy
    respond_to do |format|
      format.html { redirect_to detalhes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detalhe
      @detalhe = Detalhe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detalhe_params
      params.require(:detalhe).permit(:item_id_id, :quantidade)
    end
end

app/helpers/detalhes_helper.rb
module DetalhesHelper
end

app/views/detalhes/_form.html.erb
<%= form_for(@detalhe) do |f| %>
  <% if @detalhe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detalhe.errors.count, "error") %> prohibited this detalhe from being saved:</h2>

      <ul>
      <% @detalhe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.text_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :quantidade %><br>
    <%= f.number_field :quantidade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/detalhes/edit.html.erb
<h1>Editing detalhe</h1>

<%= render 'form' %>

<%= link_to 'Show', @detalhe %> |
<%= link_to 'Back', detalhes_path %>

app/views/detalhes/index.html.erb
<h1>Listing detalhes</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantidade</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @detalhes.each do |detalhe| %>
      <tr>
        <td><%= detalhe.item_id %></td>
        <td><%= detalhe.quantidade %></td>
        <td><%= link_to 'Show', detalhe %></td>
        <td><%= link_to 'Edit', edit_detalhe_path(detalhe) %></td>
        <td><%= link_to 'Destroy', detalhe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detalhe', new_detalhe_path %>

app/views/detalhes/new.html.erb
<h1>New detalhe</h1>

<%= render 'form' %>

<%= link_to 'Back', detalhes_path %>

app/views/detalhes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @detalhe.item_id %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @detalhe.quantidade %>
</p>

<%= link_to 'Edit', edit_detalhe_path(@detalhe) %> |
<%= link_to 'Back', detalhes_path %>